import type { Plugin } from 'vite';

/** Attributes generated by the assistant and safe to remove from production HTML. */
export const AIUI_ASSISTANT_DATA_ATTRIBUTES = [
  'data-section-id',
  'data-wrapper-id',
  'data-component-id',
  'data-component-kind',
  'data-component-name',
  'data-route',
  'data-source-file',
  'data-source-line',
] as const;

export interface AIUIReactAssistCleanupOptions {
  /** Disable the transform without changing the build configuration. */
  enabled?: boolean;
  /** Keep selected assistant attributes in the production HTML. */
  keepAttributes?: readonly string[];
  /** Override the attributes considered assistant metadata. */
  attributes?: readonly string[];
}

function cleanupAttributes(options: AIUIReactAssistCleanupOptions): readonly string[] {
  const attributes = options.attributes ?? AIUI_ASSISTANT_DATA_ATTRIBUTES;
  const keep = new Set(options.keepAttributes ?? []);
  return attributes.filter((attribute) => !keep.has(attribute));
}

function attributePattern(attributes: readonly string[]): RegExp {
  const names = attributes.map((name) => name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|');
  return new RegExp(`\\s+(?:${names})\\s*=\\s*(?:"[^"]*"|'[^']*'|[^\\s>]+)`, 'gi');
}

/** Removes assistant metadata from HTML tags while leaving text, scripts and CSS intact. */
export function cleanupAIUIHtml(
  html: string,
  attributes: readonly string[] = AIUI_ASSISTANT_DATA_ATTRIBUTES,
): string {
  if (!html || attributes.length === 0) return html;
  const attr = attributePattern(attributes);
  return html.replace(/<([a-z][^<>]*?)>/gis, (tag) => tag.replace(attr, ''));
}

function cleanAssetSource(source: unknown, attributes: readonly string[]): string | null {
  if (typeof source === 'string') return cleanupAIUIHtml(source, attributes);
  if (source && typeof source === 'object' && 'source' in source) {
    const value = (source as { source?: unknown }).source;
    return typeof value === 'string' ? cleanupAIUIHtml(value, attributes) : null;
  }
  return null;
}

/** Vite plugin for Vite, Astro and any tool that consumes Vite HTML output. */
export function AIUIReactAssistCleanup(
  options: AIUIReactAssistCleanupOptions = {},
): Plugin {
  const attributes = cleanupAttributes(options);
  const enabled = options.enabled ?? true;
  return {
    name: 'aiui-react-assist-cleanup',
    apply: 'build',
    enforce: 'post',
    transformIndexHtml(html) {
      return enabled ? cleanupAIUIHtml(html, attributes) : html;
    },
    generateBundle(_outputOptions, bundle) {
      if (!enabled) return;
      for (const [fileName, asset] of Object.entries(bundle)) {
        if (!fileName.endsWith('.html')) continue;
        const cleaned = cleanAssetSource(asset, attributes);
        if (cleaned !== null && typeof asset === 'object' && 'source' in asset) {
          (asset as { source: string }).source = cleaned;
        }
      }
    },
  };
}

/** Webpack plugin used by Next.js production builds. No webpack dependency is required. */
export class AIUIReactAssistCleanupWebpackPlugin {
  private readonly attributes: readonly string[];

  constructor(options: AIUIReactAssistCleanupOptions = {}) {
    this.attributes = cleanupAttributes(options);
  }

  apply(compiler: {
    webpack: { sources: { RawSource: new (source: string) => unknown } };
    hooks: {
      compilation: { tap: (name: string, callback: (compilation: any) => void) => void };
    };
  }): void {
    compiler.hooks.compilation.tap('AIUIReactAssistCleanup', (compilation) => {
      const stage = compilation.constructor?.PROCESS_ASSETS_STAGE_OPTIMIZE_TRANSFER ?? 4000;
      compilation.hooks.processAssets.tap(
        { name: 'AIUIReactAssistCleanup', stage },
        (assets: Record<string, { source: () => string; size?: () => number }>) => {
          for (const [fileName, asset] of Object.entries(assets)) {
            if (!fileName.endsWith('.html')) continue;
            const source = asset.source();
            const cleaned = cleanupAIUIHtml(source, this.attributes);
            if (cleaned !== source) {
              compilation.updateAsset(fileName, new compiler.webpack.sources.RawSource(cleaned));
            }
          }
        },
      );
    });
  }
}

/** Wrap a Next.js config and clean emitted production HTML assets. */
export function withAIUIReactAssistCleanup<T extends Record<string, any>>(
  nextConfig: T = {} as T,
  options: AIUIReactAssistCleanupOptions = {},
): T {
  const originalWebpack = nextConfig.webpack;
  return {
    ...nextConfig,
    webpack(config: any, context: any) {
      const nextConfigResult = originalWebpack ? originalWebpack(config, context) : config;
      if (options.enabled === false || context?.dev) return nextConfigResult;
      nextConfigResult.plugins = [
        ...(nextConfigResult.plugins ?? []),
        new AIUIReactAssistCleanupWebpackPlugin(options),
      ];
      return nextConfigResult;
    },
  } as T;
}
